version: '3'

services:
  mosquitto:
    image: eclipse-mosquitto:2
    container_name: mqtt_broker
    ports:
      - "1883:1883"  # MQTT port
      - "9001:9001"  # MQTT over WebSocket (optional)
    volumes:
      - /root/mosquitto/config
      - /root/mosquitto/data
      - /root/mosquitto/log
    networks:
      - mqtt_network


  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    networks:
      - mqtt_network


  redis:
    image: redis
    container_name: my-redis-container
    ports:
      - "6379:6379"
    networks:
      - mqtt_network


networks:
  mqtt_network:
    driver: bridge


